#!/usr/bin/env python3
"""Train an Isolation Forest from the WAAP agent's normal-traffic CSV."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import IsolationForest


# Only request/response-derived numerical fields are model inputs.  URL, method,
# timestamp, label and source are deliberately excluded to avoid memorising them.
FEATURE_COLUMNS = [
    "status_code",
    "response_time_ms",
    "url_length",
    "body_length",
    "entropy",
    "n_params",
    "has_suspicious_chars",
    "param_max_length",
    "special_char_ratio",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train Isolation Forest with normal WAAP traffic and save model.pkl."
    )
    parser.add_argument(
        "--normal-csv",
        default="logs/features_normal_traffic.csv",
        help="CSV with normal traffic generated by agent.py (default: %(default)s)",
    )
    parser.add_argument(
        "--model-output",
        default="model.pkl",
        help="Output file for the trained artifact (default: %(default)s)",
    )
    parser.add_argument("--n-estimators", type=int, default=200)
    parser.add_argument(
        "--contamination",
        type=float,
        default=0.10,
        help="Expected anomaly proportion used to set the decision threshold (default: %(default)s)",
    )
    parser.add_argument("--random-state", type=int, default=42)
    args = parser.parse_args()
    if args.n_estimators < 1:
        parser.error("--n-estimators must be at least 1")
    if not 0 < args.contamination <= 0.5:
        parser.error("--contamination must be greater than 0 and at most 0.5")
    return args


def as_bool_number(series: pd.Series) -> pd.Series:
    """Accept bools and their common CSV encodings, preserving missing values."""
    return series.replace({"True": 1, "False": 0, "true": 1, "false": 0, True: 1, False: 0})


def load_training_features(path: Path) -> pd.DataFrame:
    if not path.is_file():
        raise FileNotFoundError(f"No se encontró el CSV: {path}")

    data = pd.read_csv(path)
    missing = [column for column in FEATURE_COLUMNS if column not in data.columns]
    if missing:
        raise ValueError(f"Faltan columnas requeridas: {', '.join(missing)}")

    # Defensive filter: the normal-only CSV already complies, but this prevents
    # accidental training with attacks if another file is supplied.
    if "label" in data.columns:
        data = data[data["label"].astype(str).str.lower().eq("normal")].copy()

    features = data[FEATURE_COLUMNS].copy()
    features["has_suspicious_chars"] = as_bool_number(features["has_suspicious_chars"])
    features = features.apply(pd.to_numeric, errors="coerce")
    features = features.replace([float("inf"), float("-inf")], pd.NA).dropna()

    if len(features) < 20:
        raise ValueError(
            f"Solo quedaron {len(features)} filas normales utilizables; se recomiendan al menos 20."
        )
    return features


def main() -> None:
    args = parse_args()
    training_path = Path(args.normal_csv)
    model_path = Path(args.model_output)
    X_train = load_training_features(training_path)

    model = IsolationForest(
        n_estimators=args.n_estimators,
        contamination=args.contamination,
        random_state=args.random_state,
        n_jobs=-1,
    )
    model.fit(X_train)

    # Store the estimator with its feature contract and training metadata.
    # At inference: artifact["model"].predict(X[artifact["feature_columns"]])
    artifact = {
        "model": model,
        "feature_columns": FEATURE_COLUMNS,
        "training_rows": len(X_train),
        "contamination": args.contamination,
        "trained_at": datetime.now(timezone.utc).isoformat(),
    }
    model_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(artifact, model_path)

    print("Modelo entrenado correctamente")
    print(f"  Filas normales usadas: {len(X_train)}")
    print(f"  Features: {len(FEATURE_COLUMNS)}")
    print(f"  Contamination: {args.contamination}")
    print(f"  Archivo creado: {model_path.resolve()}")


if __name__ == "__main__":
    main()
